-- migrate:up
CREATE TYPE anchor_kind AS ENUM ('ORDER', 'SUBSCRIPTION_CYCLE');
CREATE TYPE case_state AS ENUM (
  'NEW', 'ENRICHING', 'DIAGNOSING', 'POLICY_EVAL', 'ACTION_READY', 'EXECUTING',
  'AWAITING_CUSTOMER', 'ATTEMPT_FAILED', 'AMBIGUOUS', 'RECONCILING', 'HALTED',
  'ESCALATED', 'VERIFIED_RECOVERED', 'VERIFIED_FAILED', 'EXPIRED_UNRESOLVED'
);
CREATE TYPE action_type AS ENUM ('RETRY_CHARGE', 'CREATE_PAYMENT_LINK', 'ESCALATE');
CREATE TYPE action_status AS ENUM (
  'PROPOSED', 'LIVE', 'UNRESOLVED', 'TERMINAL_SUCCESS', 'TERMINAL_FAILED', 'SUPERSEDED'
);
CREATE TYPE attempt_state AS ENUM ('PREPARED', 'IN_FLIGHT', 'ACCEPTED', 'REJECTED', 'UNKNOWN');
CREATE TYPE request_outcome AS ENUM (
  'IN_FLIGHT', 'ACCEPTED', 'REJECTED', 'TIMEOUT', 'TRANSPORT_ERROR', 'DUPLICATE_REFERENCE'
);
CREATE TYPE policy_verdict AS ENUM ('ALLOW', 'ESCALATE', 'NO_ACTION');
CREATE TYPE diagnosis_source AS ENUM ('LLM', 'DETERMINISTIC_FALLBACK');
CREATE TYPE review_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED');
CREATE TYPE breaker_state AS ENUM ('CLOSED', 'OPEN');
CREATE TYPE webhook_resolution AS ENUM ('RESOLVED', 'IGNORED', 'UNMAPPABLE', 'MALFORMED');
CREATE TYPE sim_arm AS ENUM ('CONTROL', 'TREATMENT');

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'recovery_app') THEN
    CREATE ROLE recovery_app LOGIN PASSWORD 'recovery_app_test';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'recovery_verifier') THEN
    CREATE ROLE recovery_verifier LOGIN PASSWORD 'recovery_verifier_test';
  END IF;
END
$$;

-- migrate:down
DROP ROLE IF EXISTS recovery_verifier;
DROP ROLE IF EXISTS recovery_app;
DROP TYPE IF EXISTS sim_arm;
DROP TYPE IF EXISTS webhook_resolution;
DROP TYPE IF EXISTS breaker_state;
DROP TYPE IF EXISTS review_status;
DROP TYPE IF EXISTS diagnosis_source;
DROP TYPE IF EXISTS policy_verdict;
DROP TYPE IF EXISTS request_outcome;
DROP TYPE IF EXISTS attempt_state;
DROP TYPE IF EXISTS action_status;
DROP TYPE IF EXISTS action_type;
DROP TYPE IF EXISTS case_state;
DROP TYPE IF EXISTS anchor_kind;
